64Q:
  - mux: 10
    ctrl: [qube104-2, qube104-4, qube104-9, qube104-11]
    read_out: qube104-1
    read_in: qube104-0
    pump: qube104-3
  # - mux: 14
  #   ctrl: [qube106-3, qube106-1, qube106-2, qube106-4]
  #   read_out: [qube104-7]
  #   read_in: qube104-8
  #   pump: qube104-9
